

                            <li class="menu2" onmouseover="this.className='menu1'" onmouseout="this.className='menu2'" >
                                <h2>
                                    <a target="_blank" href='[field:typeurl/]' [field:rel/] title="[field:typename/]">
                                        [field:typename/]
                                    </a>
                                </h2>
     
                            </li>
                            