<?php
$z[0]=Array("global","",141,167);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",219,249);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",285,312);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",423,455);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",665,697);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",778,810);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",884,916);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",976,1001);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",1049,1081);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1400,1432);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",2503,2528);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\n\n                            <li class=\"menu2\" onmouseover=\"this.className='menu1'\" onmouseout=\"this.className='menu2'\" >\n                                <h2>\n                                    <a target=\"_blank\" href='[field:typeurl/]' [field:rel/] title=\"[field:typename/]\">\n                                        [field:typename/]\n                                    </a>\n                                </h2>\n     \n                            </li>\n                            ",2755,3396);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li class='hover'><h2><a href='~typelink~' ~rel~ title=";
$z[11][4]['~typename~">~typename~</a></h2></li>"']="";

?>